
<!-- \subsection{Financial cycle components} -->

<!-- ```{r get_components_reg} -->

<!-- components_list = list(Credit = "Total_Credit_real_ret", -->
<!--                        HousePrice = "HousePrice_real_ret", -->
<!--                        SharePrice = "SharePrice_real_ret", -->
<!--                        FinCycle = "FinCycle_ret") -->

<!-- if("FinCycle" %in% names(components_list)){ -->
<!--   country_df = country_df %>%  -->
<!--   rowwise() %>%  -->
<!--   mutate("FinCycle_ret" = mean(Total_Credit_real_ret, HousePrice_real_ret)) -->
<!--   } -->

<!-- res_list = lapply(names(components_list), function(temp_name){ -->

<!--   source_name = components_list[[temp_name]] -->

<!--   target_name = paste0(temp_name,"_synch") -->

<!--   temp_df = country_df %>%  -->
<!--   select(Date, Country, source_name) %>%  -->
<!--   get.neg.abs.diff() %>%  -->
<!--   rename(!!sym(target_name) := !!sym(source_name)) -->


<!--   return(plm(formula = gsub("Fin_synch",target_name,reg_formula, -->
<!--                             fixed = TRUE) %>%  -->
<!--                formula(), -->
<!--              data = fin_reg_df %>%  -->
<!--                left_join(.,temp_df, by = c("Date","CountryPair")), -->
<!--              model = "within",effect = "twoways", -->
<!--              index = c("CountryPair","Date"))) -->


<!-- }) -->

<!-- names(res_list) = names(components_list) -->



<!-- ``` -->


<!-- ```{r get_components_tables, include=FALSE} -->

<!-- tables_list = lapply(names(res_list), function(temp_name){ -->

<!--   star = stargazer(res_list[[temp_name]], header = FALSE,digits = 2, -->
<!--           label = temp_name,table.placement = "H", -->
<!--           title = paste0("Financial synchronization and banking integration: ", -->
<!--                          "panel specification"), -->
<!--           dep.var.caption = paste(temp_name,"cycle synch"), -->
<!--           model.numbers = FALSE, -->
<!--           dep.var.labels.include = FALSE, -->
<!--           notes = paste0("\\parbox[t]{8cm}{", -->
<!--                          paste0("The table presents panel estimation that ", -->
<!--                                 "includes twoway fixed effects", -->
<!--                                 " and country-pair ", -->
<!--                                 " specific linear time trend. ", -->
<!--                                 notes_str_ctrl,"}")), -->
<!--           notes.align = "l", -->
<!--           notes.append = FALSE, -->
<!--           se = list(sqrt(diag(vcovHC(res_list[[temp_name]], -->
<!--                                      cluster = "group")))), -->
<!--           keep = paste0("^",temp_names,"$"), -->
<!--           order = paste0("^",temp_names,"$"), -->
<!--           covariate.labels = temp_labels, -->
<!--           omit.stat = c("f","adj.rsq")) -->

<!--   star = sub("\\textit{Note:}  & \\multicolumn{1}{l}{\\parbox[t]{8cm}{", -->
<!--              "\\multicolumn{2}{l}{\\parbox[t]{10cm}{\\textit{Note:} ", -->
<!--              star,fixed = TRUE) -->

<!--   return(star) -->



<!-- }) -->

<!-- ``` -->


<!-- ```{r output_credit_table, results="asis"} -->

<!-- cat(tables_list[[1]],sep = "\n")   -->



<!-- ``` -->


<!-- ```{r output_house_table, results="asis"} -->

<!-- cat(tables_list[[2]],sep = "\n")   -->



<!-- ``` -->


<!-- ```{r output_shares_table, results="asis"} -->

<!-- cat(tables_list[[3]],sep = "\n")   -->



<!-- ``` -->

\subsection{No trend}

In this section, I exclude the country-pair specific linear trend in order to test the robustness of my estimation. Table \ref{no_trend} presents the results.


```{r estimation_no_trend}

# reg_no_trend_formula = paste("Fin_synch ~ lag(bank_gdp,1) * Crises",
#                              "lag(bank_gdp,1) * FD_tot",
#                              "lag(bank_gdp,1) * Euro_both",
#                              "lag(bank_gdp,1) * Common_Lang",
#                              paste(control_vars, collapse = "+"),
#                              sep = "+")


# reg_list$no_trend = plm(formula = formula(reg_no_trend_formula),
#                    data = fin_reg_df,
#                    model = "within",effect = "twoways",
#                    index = c("CountryPair","Date"))


reg_list$no_trend = plm(formula = sub("+CountryPair:Time_Trend","",
                                      reg_formula, fixed = TRUE),
                   data = fin_reg_df,
                   model = "within",effect = "twoways",
                   index = c("CountryPair","Date"))


```


```{r output_no_trend, include=FALSE}


star_no_trend = stargazer(reg_list$no_trend, header = FALSE,digits = 2,
          label = "no_trend",table.placement = "H",
          title = paste0("Financial synchronization and banking integration: ",
                         "specification with no trend"),
          dep.var.caption = "Fin cycles synch",
          model.numbers = FALSE,
          dep.var.labels.include = FALSE,
          notes = paste0("\\parbox[t]{8cm}{",
                         paste0("The table presents panel estimation that ",
                                "includes twoway fixed effects. ",
                                notes_str_ctrl),"}"),
          notes.align = "l",
          notes.append = FALSE,
          se = list(sqrt(diag(vcovHC(reg_list$no_trend,cluster = "group")))),
          keep = paste0("^",temp_names,"$"),order = paste0("^",temp_names,"$"),
          covariate.labels = temp_labels,
          omit.stat = c("f","adj.rsq"))

star_no_trend = sub("\\textit{Note:}  & \\multicolumn{1}{l}{\\parbox[t]{8cm}{",
                    "\\multicolumn{2}{l}{\\parbox[t]{10cm}{\\textit{Note:} ",
                    star_no_trend,fixed = TRUE)


```


```{r output_no_trend_table, results="asis"}

cat(star_no_trend,sep = "\n")

```




<!-- Regression analysis lagged regression-->


```{r estimation_reg_lag, eval=FALSE}

reg_lag_formula = paste("Fin_synch ~ lag(bank_gdp,1) * lag(Crises, 1)",
                             "lag(bank_gdp,1) * lag(FD_tot, 1)",
                             "lag(bank_gdp,1) * lag(Euro_both, 1)",
                             "lag(bank_gdp,1) * lag(Common_Lang, 1)",
                             paste(control_vars, collapse = "+"),
                             sep = "+")


reg_list$reg_lag = plm(formula = reg_formula %>% 
                         gsub(pattern = "Crises",
                              replacement = "lag\\(Crises, 1\\)") %>% 
                         gsub(pattern = "FD_tot",
                              replacement = "lag\\(FD_tot, 1\\)") %>% 
                         gsub(pattern = "Common_Lang",
                              replacement = "lag\\(Common_Lang, 1\\)"),
                   data = fin_reg_df,
                   model = "within",effect = "twoways",
                   index = c("CountryPair","Date"))


```


```{r output_reg_lag, include=FALSE, eval=FALSE}


star_reg_lag = stargazer(reg_list$reg_lag, header = FALSE,digits = 2,
          label = "lagged",table.placement = "H",
          title = paste0("Financial synchronization and banking integration: ",
                         "lagged regression"),
          dep.var.caption = "Fin cycles synch",
          model.numbers = FALSE,
          dep.var.labels.include = FALSE,
          notes = paste0("\\parbox[t]{8cm}{",
                         paste0("The table presents panel estimation that ",
                                "includes twoway fixed effects. ",
                                notes_str_ctrl),"}"),
          notes.align = "l",
          notes.append = FALSE,
          se = list(sqrt(diag(vcovHC(reg_list$reg_lag,cluster = "group")))),
          keep = paste0("^",temp_names %>% 
                          gsub(pattern = "Crises",
                               replacement = "lag\\\\(Crises, 1\\\\)") %>% 
                          gsub(pattern = "FD_tot",
                               replacement = "lag\\\\(FD_tot, 1\\\\)") %>% 
                          gsub(pattern = "Common_Lang",
                               replacement = "lag\\\\(Common_Lang, 1\\\\)"),
                        "$"),
          order = paste0("^",temp_names,"$"),
          covariate.labels = temp_labels,
          omit.stat = c("f","adj.rsq"))

star_reg_lag = sub("\\textit{Note:}  & \\multicolumn{1}{l}{\\parbox[t]{8cm}{",
                    "\\multicolumn{2}{l}{\\parbox[t]{10cm}{\\textit{Note:} ",
                    star_reg_lag,fixed = TRUE)


```


<!-- \subsection{Lagged regression} -->
<!-- To test for another specification issue I run a regression where every independend variable is lagged one period. This is done in order to align the lagged banking linkages (that were lagged to address endogeneity) and other variables. The results are presented in table \ref{lagged}, all the results are quantitatively similiar to the main results. -->

```{r output_reg_lag_table, results="asis", eval=FALSE}

cat(star_reg_lag,sep = "\n")

```

