---
title: "Financial cycles synchronization and financial integration ^[I thank Yossi Yakhin (discussant), Yossi Saadon, Nimrod Segev, Jonathan Benshimol, Osnat Zohar, Yaakov Chen-Zion and the participants of the Bank of Israel Research Department seminar for their helpful comments and suggestions]"
subtitle: 'Preliminary draft'
author: "Michael Gurkov"
fontsize: 11pt
output:
  rmarkdown::pdf_document:
    # latex_engine: xelatex
    number_sections: true
    includes:
            in_header: GlobalFinCyclePreambleDoc.tex
            
abstract: "This paper studies the relationship between financial cycles synchronization and financial integration using data on 30 OECD countries. The results suggest that the relationship is state depended: While financial integration acts as \"shock absorber\" during normal times, I find that financial crises increase the \"shock propagation\" feature of banking integration. Overall the findings show that while banking integration may be desired because it may facilitate risk diversification, additional macro prudential measures may be warranted to account for the risk exposure during crisis times."

bibliography: '`r stringr::str_replace_all(paste(file.path(Sys.getenv("USERPROFILE"),"\\OneDrive - Bank Of Israel\\References\\Financial_Cycle-Global_Financial_Cycle - Copy.bib")),"\\\\","\\\\\\\\\\")`'

nocite: '@*'

vignette: >
  %\VignetteIndexEntry{CycleSynch}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,echo = FALSE,
  message = FALSE,warning = FALSE,
  comment = "#>"
)
```


```{r load_package}

devtools::load_all()

library(MiscImport)

library(lubridate)

library(tidyverse)

library(tidyselect)

library(plm)

library(stargazer)
 
library(purrr)

library(scales)

```


```{r params_setup}

countries_list = list(
  oecd_countries = c(
    "Australia",
    "Austria",
    "Belgium",
    "Canada",
    "Chile",
    "Czech_Republic",
    "Denmark",
    "Estonia",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hungary",
    "Iceland",
    "Ireland",
    "Israel",
    "Italy",
    "Japan",
    "Korea",
    "Latvia",
    "Lithuania",
    "Luxembourg",
    "Mexico",
    "Netherlands",
    "New_Zealand",
    "Norway",
    "Poland",
    "Portugal",
    "Slovak_Republic",
    "Slovenia",
    "Spain",
    "Sweden",
    "Switzerland",
    "Turkey",
    "United_Kingdom",
    "United_States"
  ),
  kpp_countries = c(
    "Australia",
    "Austria",
    "Belgium",
    "Canada",
    "Switzerland",
    "Germany",
    "Denmark",
    "Spain",
    "Finland",
    "France",
    "United_Kingdom",
    "Ireland",
    "Italy",
    "Japan",
    "Netherlands",
    "Portugal",
    "Sweden",
    "United_States"
  ),
  fsap_countries = c(
    "Austria",
    "Belgium",
    "Germany",
    "Denmark",
    "Spain",
    "France",
    "Finland",
    "Greece",
    "Ireland",
    "Italy",
    "Luxembourg",
    "Netherlands",
    "Portugal",
    "Sweden",
    "United_Kingdom"
  ),
  eu_countries = c(
    "Austria",
    "Belgium",
    "Bulgaria",
    "Croatia",
    "Cyprus",
    "Czech_Republic",
    "Denmark",
    "Estonia",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hungary",
    "Ireland",
    "Italy",
    "Latvia",
    "Lithuania",
    "Luxembourg",
    "Malta",
    "Netherlands",
    "Poland",
    "Portugal",
    "Romania",
    "Slovak_Republic",
    "Slovenia",
    "Spain",
    "Sweden",
    "United_Kingdom"
  ),
  euro_countries = c(
    "Austria",
    "Belgium",
    "Cyprus",
    "Estonia",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Ireland",
    "Italy",
    "Latvia",
    "Lithuania",
    "Luxembourg",
    "Malta",
    "Netherlands",
    "Portugal",
    "Slovak_Republic",
    "Slovenia",
    "Spain"
  )
)


pairs_list = lapply(names(countries_list),
                    function(temp_name){
                      apply(combn(countries_list[[temp_name]],2), 2,
                            function(temp_col){
                              ifelse(temp_col[1]<temp_col[2],
                                     paste(temp_col[1],temp_col[2],sep = "-"),
                                     paste(temp_col[2],temp_col[1],sep = "-"))})

                    })

names(pairs_list) = paste(names(countries_list), "pairs", sep = "_")

countries_list = c(countries_list, pairs_list)

rm(pairs_list)

reg_list = list()

control_vars = c("trade_gdp","FX_stab_tot","FO_ind_tot","GDP_real_tot")



```


```{r child="Import_Data.Rmd"}

```
